updated parallel rdf script and enabled it to use 1 to 99 separate processes through the settings file

diff --git a/code_and_scripts/scripts/multi_g_rdf b/code_and_scripts/scripts/multi_g_rdf
--- a/code_and_scripts/scripts/multi_g_rdf
+++ b/code_and_scripts/scripts/multi_g_rdf
@@ -1,6 +1,6 @@
 #! /bin/bash
 #
-# Copyright 2009-2011 The VOTCA Development Team (http://www.votca.org)
+# Copyright 2009-2016 The VOTCA Development Team (http://www.votca.org)
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -15,6 +15,8 @@
 # limitations under the License.
 #
 
+#version 2.0 -- 19.10.15 standalone version
+
 g_cmd=${0##*/}
 g_cmd=${g_cmd#multi_}
 fbase=${g_cmd#g_}
@@ -24,7 +26,7 @@ end=""
 np=8
 index="index.ndx"
 out="${fbase}.xvg"
-version="1.2.4 "
+version="$(sed -ne 's/^#version \(.*\) -- .*$/\1/p' "$0" | sed -n '$p')"
 single="no"
 debug="no"
 
@@ -53,7 +55,7 @@ ${0##*/}, version ${version}
 
 
 
-This is a multiplexed version of $g_cmd
+This is a multiplexed version of $g_cmd.
 
 Usage: ${0##*/} [OPTIONS] -- [${g_cmd}_options]
 
@@ -71,7 +73,7 @@ Allowed options:
                     Default: ${out%.xvg}_NP.xvg (used trunc of name given by -o)
 		    (where NP is replaced later by the number of the process)
     --log FILE      Name of logfile
-                    Default: ${out%.xvg}_NP.log" (used trunc of name given by -o)
+                    Default: ${out%.xvg}_NP.log (used trunc of name given by -o)
 		    (where NP is replaced later by the number of the process)
     --cmd CMD       Change the gromacs command to run
                     Default: ${g_cmd}
@@ -99,7 +101,7 @@ while [ "${1#-}" != "$1" ]; do
    -[0-9]* | --[0-9]**)
     np=${1#-}
     np=${np#-}
-    [ -z "${np//[0-9]}" ] || die "$1 could not be convert to a number"
+    [ -z "${np//[0-9]}" ] || die "$1 could not be converted to a number"
     shift ;;
    -b)
     begin="$2"
@@ -154,6 +156,7 @@ dt="$(awk -v b="$begin" -v e="$end" -v np="$np" 'BEGIN{print (e-b)/np}')"
 [ -z "$dt" ] && die "Could not calculate dt"
 
 [ -f "$index" ] || die "Indexfile $index not found"
+
 echo "Select a reference group and 1 group"
 sed -n 's/.*\[\(.*\)\].*/\1/p' $index | awk '{print "Group",NR-1,"(",$0,")"}'
 echo -n "Select a group: "
